### ISSUE TITLE
zmq.so mach-o, but wrong architecture

### ISSUE THREAD

**Issue by dmitrybelyakov** [zeromq/php-zmq#20]
Hi Mikko,

I am trying to make it work on my OSX 10.6.6 and it compiles fine as far as I can tell, but i get this in apache logs when starting up:

[21-Mar-2011 00:31:56] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/zend/lib/php_extensions/zmq.so' - dlopen(/usr/local/zend/lib/php_extensions/zmq.so, 9): no suitable image found.  
Did find: /usr/local/zend/lib/php_extensions/zmq.so: mach-o, but wrong architecture in Unknown on line 0

Any advise on what can be tweaked to make this work?

**Comment by kiradotee** [comment]
Worked for me(-ish)*:

    phpize
    CFLAGS="-arch i386" LDFLAGS="-arch i386" ./configure
    make
    make install

Then I moved the extension from the auto-created folder into the normal `.../php/extensions/ext/`

\* ish because .so seems to be working and PHP recognises it as an extension but then fails:

    dyld: lazy symbol binding failed: Symbol not found: _zmq_version
      Referenced from: /Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so
      Expected in: flat namespace

    dyld: Symbol not found: _zmq_version
      Referenced from: /Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so
      Expected in: flat namespace
