### ISSUE TITLE
failure to build on ubuntu 12.04

### ISSUE THREAD

**Issue by richo** [zeromq/php-zmq#69]
With the php and zeromq development headers installed, we can no longer build the extension, it appears to be as a result of f5197006d7c517d0014eca2b14fa3139017c67cd

```
   /bin/bash /tmp/pear/temp/pear-build-rootSTKOPM/zmq-1.0.4/libtool --mode=compile cc  -I. -I/tmp/pear/temp/zmq -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootSTKOPM/zmq-1.0.4/include -I/tmp/pear/temp/pear-build-rootSTKOPM/zmq-1.0.4/main -I/tmp/pear/temp/zmq -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/zmq/zmq.c -o zmq.lo
    libtool: compile:  cc -I. -I/tmp/pear/temp/zmq -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootSTKOPM/zmq-1.0.4/include -I/tmp/pear/temp/pear-build-rootSTKOPM/zmq-1.0.4/main -I/tmp/pear/temp/zmq -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/zmq/zmq.c  -fPIC -DPIC -o .libs/zmq.o
    /tmp/pear/temp/zmq/zmq.c:1433:2: error: 'zim_zmqcontext_setOpt' undeclared here (not in a function)
    /tmp/pear/temp/zmq/zmq.c:1434:2: error: 'zim_zmqcontext_getOpt' undeclared here (not in a function)
    /tmp/pear/temp/zmq/zmq.c:1504:2: error: 'zim_zmqsocket_unbind' undeclared here (not in a function)
    /tmp/pear/temp/zmq/zmq.c:1504:2: error: initializer element is not constant
    /tmp/pear/temp/zmq/zmq.c:1504:2: error: (near initialization for 'php_zmq_socket_class_methods[7].handler')
    /tmp/pear/temp/zmq/zmq.c:1505:2: error: 'zim_zmqsocket_disconnect' undeclared here (not in a function)
    /tmp/pear/temp/zmq/zmq.c:1505:2: error: initializer element is not constant
    /tmp/pear/temp/zmq/zmq.c:1505:2: error: (near initialization for 'php_zmq_socket_class_methods[8].handler')
    make: *** [zmq.lo] Error 1
    ERROR: `make' failed
```
